---
swagger: "2.0"
info:
  description: "Postman Testing Example"
  version: "1.0.0"
  title: "Postman Testing Example"
host: "localhost:8080"
basePath: "/"
schemes:
- "http"
paths:
  /products:
    get:
      operationId: "productsGET"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            properties:
              data:
                type: "array"
                items:
                  $ref: "#/definitions/Product"
      x-swagger-router-controller: "Default"
  /products/{id}:
    get:
      operationId: "productsIdGET"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "OK"
          schema:
            properties:
              data:
                $ref: "#/definitions/Product"
      x-swagger-router-controller: "Default"
  /users:
    get:
      operationId: "usersGET"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            properties:
              data:
                type: "array"
                items:
                  $ref: "#/definitions/User"
      x-swagger-router-controller: "Default"
  /users/{id}:
    get:
      operationId: "usersIdGET"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "OK"
          schema:
            properties:
              data:
                $ref: "#/definitions/User"
      x-swagger-router-controller: "Default"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 1
      type:
        type: "string"
        example: "users"
      attributes:
        $ref: "#/definitions/User_attributes"
  Product:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 1
      type:
        type: "string"
        example: "products"
      attributes:
        $ref: "#/definitions/Product_attributes"
  User_attributes:
    properties:
      email:
        type: "string"
        example: "hello@bornfight.com"
  Product_attributes:
    properties:
      name:
        type: "string"
        example: "Product #1 Name"
      description:
        type: "string"
        example: "Product #1 Description"
